Photoroom/datago

.github/workflows/go.yml
.github/workflows/gopy.yml

Setting up an automatic compilation of the python module on every pull request. Next are python tests, then pypi update on release

[CI] Build gopy package on the fly

---

src/pkg/client/client.go
src/pkg/client/frontend_db.go

Step by step to improve on #9. Per source, we need 
- a front end which will generate pages of data pointers
- a back end which will go through them appropriately to deserialize the payloads, do optional picture processing and serialization
First step in a series, should make it easier to add
- loading from local files
- loading from object storage

[arch] Adding a more flexible frontend architecture

---

src/pkg/client/backend_http.go
src/pkg/client/client.go
src/pkg/client/frontend_db.go
src/pkg/client/serdes.go

Everything becomes around Datago, Dataroom client is a specific incarnation

[Refactor] Remove references to Dataroom in the types

---

README.md

Measure twice and cut once, as the saying goes

[hotfix] Better readme, better late than sorry

---

.github/workflows/ci-cd.yml

[CD] Another hotfix, include manifest to get a correct sdist

---

.github/workflows/go.yml
.gitignore
generate_python_package.sh
pkg/generator_filesystem.go
python/benchmark_filesystem.py

[hotfix] Rank and worldsize handling in benchmark & filesystem in general

---

.github/workflows/ci-cd.yml
generate_python_package.sh
go.mod
go.sum
pkg/client.go
pkg/worker_filesystem.go
pkg/worker_http.go
python/benchmark_filesystem.py

- auto GOMAXPROCS
- some uarch optims, won't change much (since most of the compute is in vips)

[perf] Tentative perf fix for the pypi package (local builds were fast already)

---

cmd/main.go
pkg/architecture.go
pkg/client.go
pkg/generator_db.go
pkg/generator_filesystem.go
pkg/serdes.go
pkg/utils.go
python/benchmark_db.py
python/benchmark_filesystem.py
python/go_types.py
python/test_datago_db.py

Doesn't seem to affect speed, doing more tests to make sure. Goal is to fix a mem leak which seems to happen in high throughput situations (cc @tarek-ayed )

[gopy] Cleaner bytes buffer transfer

---

README.md
tests/client_db_test.go
tests/client_filesystem_test.go

plugging the holes step by step

[CI] Basic filesystem path unit test

---

.github/workflows/ci-cd.yml
.github/workflows/go.yml

giving this empirical cue a shot

[ci] Lock Go to 1.18.1

---

pkg/serdes.go
tests/client_db_test.go

Fixes https://github.com/Photoroom/datago/issues/46

[DB API] Add random sampling support

---

pkg/generator_db.go
pkg/serdes.go
tests/client_db_test.go

Fixes https://github.com/Photoroom/datago/issues/48 + Unit test

[DB API] Respect Sources NE

---

README.md
pkg/client.go
pkg/generator_db.go
tests/client_db_test.go

fix https://github.com/Photoroom/datago/issues/52, added a unit test to nail it

[nit] Gracefully report missing env variable instead of panicking

---

pkg/core.go
pkg/serdes.go
python/go_types.py

Fix https://github.com/Photoroom/datago/issues/57

[feat] Supporting 16bits images

---

cmd/main.go
pkg/client.go

Now happily going through image net a 1000 samples/second on a laptop :)

[nit] Demo was stuck to 2000 samples..

---

pkg/client.go
pkg/serdes.go
pkg/worker_filesystem.go

[This](https://github.com/davidbyttow/govips/blob/8d9c5493bcbc5b0cceb6467fb3fdc53c9fe984d4/vips/image.go#L613) was a good hint, should have thought of it earlier

[core] Release vips image when done, remove GC work

---

.github/workflows/rust-py.yml
.github/workflows/rust.yml
Cargo.lock
Cargo.toml
python/benchmark_filesystem.py
python/dataset.py
python/test_datago_db.py
python/test_datago_filesystem.py
src/client.rs
src/generator_files.rs
src/generator_http.rs
src/image_processing.rs
src/lib.rs
src/main.rs
src/structs.rs
src/worker_files.rs
src/worker_http.rs

[x] general refactor, not perfect but cleaner and more flexible
[x] file serve support
[x] fix all the python unit tests across both DB and file

[Rust] Add file serve support & refactor

---

src/client.rs
src/generator_http.rs

cc @tarek-ayed, should fix your issue

[hotfix] Pager thread finicky + short time out

---

Cargo.lock
Cargo.toml
src/client.rs
src/generator_files.rs
src/generator_http.rs
src/worker_files.rs
src/worker_http.rs

title, almost nothing
edit: adding some minor fixes while I'm at it (reduced verbosity and more optimized build)

[lint] nit fixs + new version to update the pip package to 2025.3.10

---

Cargo.lock
Cargo.toml
python/test_datago_filesystem.py
src/client.rs
src/generator_http.rs
src/image_processing.rs
src/main.rs
src/worker_files.rs
src/worker_http.rs
tests/client_test.rs

better handling of rgb8, removing some code duplication

---

Cargo.lock
Cargo.toml
src/image_processing.rs

tradeoff with size, can be changed now that the settings are more or less exposed

[faster PNG] Remove CPU bottleneck if many image payloads

---

Cargo.lock
Cargo.toml
README.md
src/generator_http.rs
tests/client_test.rs

* Added a necessary step to setup the project on apple silicon macs in the README
* Added a test for pixel count filtering
* Added attributes dict filtering
* Added tags__ne_all, tags__all and tags__empty filters

Add attributes and tags filters

---

src/client.rs
src/main.rs
src/structs.rs
src/worker_files.rs
src/worker_http.rs

"Fixes" #107, but not clear it was broken to begin with
Some cosmetic changes in the meantime

Relaxed timeout for main client IO

---

python/benchmark_webdataset.py
src/client.rs
src/generator_files.rs
src/generator_http.rs
src/generator_wds.rs
src/structs.rs
src/worker_files.rs
src/worker_wds.rs

related to #116 and #115, a little more involved

Cleaner WDS take, one less thread
