Photoroom/datago

src/cmd/main/main.go
src/pkg/client/client.go
src/pkg/client/serdes.go
src/pkg/client/transforms.go
src/tests/client_test.go

- request a config structure upon construction, named fields so less error prone
- backport more tests + env define via DATAROOM_TEST_SOURCE

[backports] Cleaner construction via config structure, more tests

---

src/pkg/client/backend_http.go
src/pkg/client/client.go
src/pkg/client/serdes.go

Another step towards #9. 
Eventually Datago will be a dataloader which is organized around a frontend (generates pointers to data) and backend (fetch, deserialize, process, serialize). 
Several frontends and backend are quite easy to implement, currently there's only a DB frontend with a HTTP backend, but adding support for local files or a S3 bucket enumerator and client wouldn´t be too complicated

[arch] Make it possible to have different backends

---

.github/workflows/go.yml
pkg/client.go
tests/client_test.go

[CI] Mega nit, add race condition detection to the tests & fix race to log

---

pkg/generator_db.go
pkg/serdes.go
tests/client_db_test.go

this changed over time, and public package got stuck to the old API

[nitfix] Not handling multiple sources correctly

---

pkg/generator_db.go
pkg/serdes.go
tests/client_db_test.go

* When implementing duplicate_state filtering, I found out that returnDuplicateState wasn't working properly (missing one declaration in `serdes.go` 
* Added an interface to request only samples with a certain duplicate state

fix returnDuplicateState option and add duplicate_state filtering

---

pkg/serdes.go
python/test_datago_db.py

python space expects bits, datago was communicating bytes, hard disagree.. fixing this + adding a test to catch this issue

[hotfix] bits and bytes disagreeing

---

.github/workflows/ci-cd.yml
.github/workflows/go.yml
.github/workflows/gopy.yml

go 1.22 is tested by gopy, here's to me hoping that it's as fast as 1.18 we were using previously (which is incompatible with the file mmap added recently)

[chore] Build package with 1.22, 1.23 is still slow

---

pkg/client.go

looks like vips can allocate a lot outside of go scope, memory use can balloon pretty fast for big images

[nit] Force frequent GC

---

.github/workflows/ci-cd.yml
.github/workflows/go.yml
go.mod
go.sum
pkg/worker_filesystem.go

gopy speed issues past 1.18 are still there, we really need to catch that in the CI/CD instead of post-build

[chore] Reverting back to go 1.18 for gopy  speed, no more mmap

---

pkg/serdes.go

ownership rules are not super clear here in between the go scope and C / vips

[hotfix] Race condition on the buffer release

---

pkg/transforms.go

missing sqrt, made no sense as is.. meant that we had way too many possible image sizes

[hotfix] Image size buckets

---

.github/workflows/go.yml
cmd/db/main.go
cmd/filesystem/main.go
pkg/client.go
pkg/generator_db.go
pkg/generator_filesystem.go
pkg/serdes.go
pkg/transforms.go
pkg/worker_filesystem.go
pkg/worker_http.go
python/benchmark_db.py
python/go_types.py
python/test_datago_db.py
tests/client_db_test.go
tests/client_filesystem_test.go
tests/transform_test.go

For some payloads vips will sigabrt on a function call, without an obvious way to catch this beforehand (initial loadbuffer doesn't error out, image characteristics have nothing specific). Happening very often on a given cluster, guess is that network could be less reliable and broken packets would not be caught somehow. 
Adding a relatively ugly but seemingly reliable defer(recover) pattern which will skip this payload for now, testing overnight. Not sure how to unit test this
Note that this PR enables img.Close()-ing the vips image when done, which lowers the RAM use quite dramatically (not waiting for the go GC)

[stability] Survive vips sigabrt

---

Cargo.lock
Cargo.toml
python/benchmark_filesystem.py
python/dataset.py
src/client.rs
src/generator_files.rs
src/generator_http.rs
src/image_processing.rs
src/main.rs
src/worker_files.rs
src/worker_http.rs
tests/client_test.rs

- No more threadpool
- Still a mechanism with a number of tasks in flight (implicit threadpool let's say), because we don´t want to materialize all the tasks if there are 2M of them. We materialize a task window which is renewed as the samples are consumed by the user. always wait on the oldest task
- One seperate lane per sample (tokio::spawn), may not be optimal, we could only spawn the CPU heavy work and keep everything else in the main async lane ?
Pretty fast.. 4000 img/s when warm (served from RAM cache) on IN1k on a 2021 laptop (no crop & resize). I never got anything close to this with Go, max 1k
addresses https://github.com/Photoroom/datago/issues/81

Async most of the Rust code

---

.pre-commit-config.yaml
Cargo.lock
Cargo.toml
README.md
pyproject.toml
python/benchmark_filesystem.py
python/test_datago_filesystem.py
src/generator_files.rs
src/generator_http.rs
src/main.rs
src/worker_files.rs

Add an option to enforce randomness on the files being served. Note that even without this setting there will be some randomness, as the different threads compete while loading files and will finish at different times. It would not be uniformly random though (which would show in ML while training on possibly big batches), so this is useful

[files] Convenience, enforce randomness

---

Cargo.lock
Cargo.toml
README.md
python/dataset.py
src/client.rs
src/generator_files.rs
src/generator_http.rs
src/image_processing.rs
src/lib.rs
src/main.rs
src/worker_files.rs
src/worker_http.rs

- Replace all printf calls with log calls.
- Expose a init_logging function to Python, which takes a log level as string or relies on RUST_LOG env var by default.
Resolves #109

Use log library

---

Cargo.lock
Cargo.toml
README.md
python/benchmark_filesystem.py
src/generator_files.rs

Remove one thread which was just serving the files into another kanal, this arch was a remnant from the original golang implementation, doesn't make too much sense in this case. Better would now to have all the file front end async calls, so that the file dispatch can be concurrent to walking through the filesystem. 
Making the python test vs. torch more fair by allowing more CPUs to torch, but when caching is removed rust is still faster. Note that image processing even things out more or less, but the datago image proc is more qualitative

[refactor] Simpler setup for files, same would probably work for the DB path

---

src/client.rs
src/generator_files.rs
src/generator_http.rs
src/structs.rs

related to #115 and #111, aligning all the paths towards a simpler setup, removing a kanal which really came from the golang implementation. Code is slightly more compact, one less thread to explicitly join, one less synchronization to pass, I think we're better for it

[refactor] DB path : simpler setup, feeder thread does the dispatch, one less kanal

---

Cargo.lock
Cargo.toml
README.md
python/benchmark_filesystem.py
python/benchmark_webdataset.py
src/client.rs
src/generator_files.rs
src/generator_wds.rs
src/lib.rs
src/main.rs
src/structs.rs
src/worker_files.rs
src/worker_http.rs
src/worker_wds.rs

cc @photoroman for early visibility

[feat] Webdataset support

---

Cargo.lock
Cargo.toml
python/benchmark_filesystem.py
src/generator_wds.rs
src/image_processing.rs
src/worker_files.rs
src/worker_http.rs
src/worker_wds.rs

On an old laptop, benchmarking over 5000 ImageNet images which are being resized on the fly.
Used to be more or less the same speed in that case in between a torch dataloader + python scope transforms (multiprocess), now 1.8x faster 
A little bit scary to change this part of the code which is now battle proof, but since we have all the wheels and we can revert anytime.. ?
handles #124

[perf] faster image processing

---

src/worker_http.rs

Better take on #127, may not be enough though

Retry image decoding on DB path

---

Cargo.lock
Cargo.toml
python/test_datago_edge_cases.py
src/client.rs
src/generator_files.rs
src/structs.rs

- one bug was not generating enough test files 
- better handling of a broken config, do not panic! (will crash the python process) but error!() (will print out the issue) and return None samples

[nit][again] Fixing CI in latest commit.. 
